controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\AccessController;
use app\models\Apartment;
use app\models\Company;
use app\models\Functions;
use app\models\House;
use app\models\Resident;
use app\models\Room;
use app\models\search\HouseSearch;
use app\models\Settings;
use app\models\UploadForm;
use app\models\User;
use app\models\Users;
use app\modules\fias\models\Dadata;
use Exception;
use PhpOffice\PhpSpreadsheet\IOFactory;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\UploadedFile;
use app\components\FcmPusher;

class SiteController extends AccessController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
//                'only' => ['logout'],
                'rules' => [
//                    [
//                        'actions' => ['index','logout'],
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
                    [
                        'actions' => ['login', 'error', 'backup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index', 'import-ls', 'import-mkd'],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['super_administrator', 'administrator', 'super_manager', 'manager', 'specialist'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $cache = Yii::$app->cache;
        $session = Yii::$app->session;
        $request = Yii::$app->request;
        /** @var Users $identity */
        $identity = Yii::$app->user->identity;

        $model = new LoginForm();
        $model->inn = $cache->get('c_inn');

        if ($request->isGet && $request->isAjax) {
            Yii::info('Enter Superadmin', 'test');
            //Если входит супер админ под пользователем

            $company_id = $request->get('company');

            if ($company_id && Users::isSuperAdmin()) {

                $company_model = Company::findOne($company_id);
                $model->username = $company_model->inn;
                $model->password = $company_model->password;
                $model->company_id = $company_model->id;
                $model->inn = $company_model->inn;

                $session->set('user_is', 'sa');
                $session->set('user_is_login', $identity->login);
                $session->set('user_is_company', $model->company_id);
            } else {
                $model->addError('error', 'Ошибка аутентификации');
            }
        } else {
            Yii::info('Normal Enter', 'test');

            if ($request->get('as_user') == 'sa') {
                $user = Users::findOne([
                    'login' => $session->get('user_is_login'),
                    'company_id' => $session->get('user_is_company')
                ]);
                $model->username = $user->login;
                $model->company_id = $user->company->id;

                $session->remove('user_is');
                $session->remove('user_is_login');
                $session->remove('user_is_company');

            } else {
                if (!$model->load(Yii::$app->request->post())) {
                    $model->password = '';
                    return $this->render('login', [
                        'model' => $model,
                    ]);
                }
            }
            Yii::info($model->toArray(), 'test');
        }
        $company = Company::findOne(['inn' => $model->inn]) ?? null;
        if (!$company) {
            $model->addError('inn', 'Неизвестный ИНН');
            return $this->render('login', [
                'model' => $model,
            ]);
        }
        Yii::info($company->enabled, 'test');

        //Проверяем блокировку компании
        if (!$company->enabled) {
            $model->addError('inn', 'Компания отключена. Обратитесь к суперадминистратору');
            return $this->render('login', [
                'model' => $model,
            ]);
        }
        if (Yii::$app->user->isGuest) {
            //Когда пользователь гость. Когда входит супер-админ - ИНН не сохраняем
            //Сохраняем ИНН
            Yii::$app->cache->set('c_inn', $company->inn);
        }
        if ($model->login()) {
            return $this->goBack();
        }

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect('login');
//        return $this->goHome();
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * @return string|Response
     */
    public function actionAuthorization()
    {
        if (isset(Yii::$app->user->identity->id)) {
            return $this->render('error');
        } else {
            Yii::$app->user->logout();
            return $this->redirect(['login']);
        }
    }

    /**
     * @throws \yii\base\Exception
     */
    public function actionBackup()
    {
        /** @var \demi\backup\Component $backup */
        $backup = Yii::$app->backup;

        $file = $backup->create();

        return 'Backup file created: ' . $file . PHP_EOL;
    }

    /**
     * @return \yii\console\Response|Response
     * @throws Exception
     */
    public function actionDownload()
    {
        $path = \Yii::getAlias('@app/runtime/logs');
        $file = $path . '/_error.log';

        if (file_exists($file)) {
            return \Yii::$app->response->sendFile($file);
        }
        throw new NotFoundHttpException('Файл не найден', 404);
    }

    /**
     * Импорт сведений о многоквартирных домах (МКД)
     * @return string|Response
     * @throws \PhpOffice\PhpSpreadsheet\Reader\Exception
     */
    public function actionImportMkd()
    {
        $model = new UploadForm();
        $request = Yii::$app->request;
        $errors = [];

        if ($request->isPost) {
            $model->file = UploadedFile::getInstance($model, 'file');
            $tmp_name = time() + rand(999, 99999999);
            ini_set('memory_limit', '256M');
            set_time_limit(600);

            if ($model->upload($tmp_name)) {
                // Файл успешно загружен
                $inputFileName = 'uploads/' . $tmp_name . '.' . $model->file->extension;

                /** Load $inputFileName to a Spreadsheet Object  **/
                $spreadsheet = IOFactory::load($inputFileName);

                //Лист с кодами домов в системе ФИАС и адресом дома
                $character_sheet = $spreadsheet->getSheetByName('Характеристики МКД');

                //Лист с номерами квартир, связь с домом по полям "Адрес" и "Адрес МКД, в котором расположено жилое/нежилое помещение"
                $residential_sheet = $spreadsheet->getSheetByName('Жилые помещения');


                $non_residential_sheet = $spreadsheet->getSheetByName('Нежилые помещения');

                $room_sheet = $spreadsheet->getSheetByName('Комнаты');

                if (!$character_sheet) {
                    Functions::setFlash('Импорт невозможен. В импортируем файле отсутствует лист "Характеристики МКД"');
                } elseif (!$residential_sheet) {
                    Functions::setFlash('Импорт невозможен. В импортируем файле отсутствует лист "Жилые помещения"');
                } elseif (!$non_residential_sheet) {
                    Functions::setFlash('Импорт невозможен. В импортируем файле отсутствует лист "Нежилые помещения"');
                } elseif (!$room_sheet) {
                    Functions::setFlash('Импорт невозможен. В импортируем файле отсутствует лист "Комнаты"');
                }

                if (Yii::$app->session->get('error') != '') {
                    return $this->redirect('import-mkd');
                }

                $character_cells = $character_sheet->getCellCollection();
                $residential_cells = $residential_sheet->getCellCollection();
                $non_residential_cells = $non_residential_sheet->getCellCollection();
                $room_cells = $room_sheet->getCellCollection();

                //$columns_num = Coordinate::columnIndexFromString($cells->getHighestColumn());

//                Yii::info('Кол-во строк: ' . $character_cells->getHighestRow(), 'test');

                //Перебираем строки листа "Характеристики МКД", начиная с третьей
                for ($row = 3; $row <= $character_cells->getHighestRow(); $row++) {

views/site/_house_columns.php
<?php

use app\models\Company;
use app\models\House;
use app\models\Users;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
     [
         'class' => '\kartik\grid\DataColumn',
         'attribute' => 'company_id',
         'label' => 'Компания',
         'filter' => Company::getList(),
         'value' => function(House $model){
                return $model->company->name ?? null;
         },
         'visible' => Users::isSuperAdmin(),
     ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'address',
        'label' => 'Адрес',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'fias_number',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'cadastral_number',
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'residential_number',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'non_residential_number',
//    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'additional_info',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'document_id',
    // ],

    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title' => 'Просмотр','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title' => 'Редактировать', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title' => 'Удалить',
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Вы уверены?',
                          'data-confirm-message'=>'Вы уверены, что хотите удалить эту запись?'],
    ],

];   

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

//$this->title = $name;
?>
<section class="content error_page">

    <div class="container">
        <div class="row">
            <div class="col-xs-3"></div>
            <div class="col-xs-6">
                <div class="error-content">
                    <h4>
                        Сожалеем, возникла непредвиденная ошибка ;(
                    </h4>
                    <h4 class="text-danger">
                        <?= $name ?> <?= nl2br(Html::encode($message)) ?>
                    </h4>
                    <p>
                        <a href=<?= Yii::$app->homeUrl ?>>Вернуться к главной странице</a>
                    </p>
                </div>
            </div>
            <div class="col-xs-3"></div>
        </div>
    </div>

</section>

views/site/import_ls.php
<?php

/* @var $this yii\web\View */

use kartik\file\FileInput;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

//$this->title =  Yii::$app->name;
?>
<div class="site-index">

    <div class="body-content">
        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="text-center">Импорт сведений о лицевых счетах</h2>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h4 class="text-danger text-bold">ВНИМАНИЕ!</h4>
                        <p>Перед импортом сведений о ЛС необходимо выполнить <?= Html::a('импорт сведений о МКД', ['/site/import-mkd']) ?> </p>
                        <p>Если этого не сделать, то жильцы не будут привязаны к домам и помещениям!</p>
                        <p>&nbsp;</p>
                    </div>
                    <div class="col-md-6 col-md-offset-3 import-form">

                        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>


                        <div class="col-md-12">
                            <?= $form->field($model, 'file')->widget(FileInput::classname(), [
                                'options' => [
                                    'multiple' => false,
                                ],
                                'pluginOptions' => [
                                    'showPreview' => false,
                                ]
                            ])->label('Выберите файл для импорта и нажмите "Загрузить"'); ?>
                        </div>

                        <?php ActiveForm::end(); ?>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

views/site/import_mkd.php
<?php

/* @var $this yii\web\View */

use kartik\file\FileInput;
use yii\bootstrap\ActiveForm;

//$this->title =  Yii::$app->name;
?>
<div class="site-index">

    <div class="body-content">
        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="text-center">Импорт сведений о многоквартирных домах</h2>
                    </div>
                    <div class="import-form col-md-6 col-md-offset-3">

                        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

                        <div class="col-md-12">
                            <?= $form->field($model, 'file')->widget(FileInput::classname(), [
                                'options' => [
                                    'multiple' => false,
                                ],
                                'pluginOptions' => [
                                    'showPreview' => false,
                                ]
                            ])->label('Выберите файл для импорта и нажмите "Загрузить"'); ?>
                        </div>

                        <?php ActiveForm::end(); ?>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title =  Yii::$app->name;
?>
<div class="site-index">

    <div class="body-content">
     <div class="box box-default">
        <div class="box-body">
        <div class="row">
            <h2 class="text-center">Добро Пожаловать</h2>

        </div>
    </div>
</div>

    </div>
</div>

views/site/instructions.php
<?php

/* @var $this yii\web\View */

use mihaildev\ckeditor\CKEditor;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'Инструкции';
$url_dir_instructions = Url::to(['/instructions'], true);
$path_instructions = Url::to('@webroot/instructions');
$files = '';
Yii::info($path_instructions, 'test');
if (is_dir($path_instructions)) {
    $files = array_diff(scandir($path_instructions), array('..', '.'));;
}
?>
<div class="site-index">

    <div class="body-content">
        <div class="box box-default">
            <div class="box-body">
                <?php if ($files): ?>
                    <?php foreach ($files as $key => $file): ?>
                        <div class="row">
                            <?= Html::a($key - 1 . '. ' . $file, $url_dir_instructions . '/' . $file); ?>
                        </div>
                    <?php endforeach; ?>
                <?php else: ?>
                    <div class="row">
                        Инструкции не найдены!
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <div class="box box-default">
            <div class="box-body">
                <?= Html::a('Описание АПИ', ['/api']) ?>
            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
$fieldOptions3 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon  glyphicon-briefcase form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><b><?=Yii::$app->name?></b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Введите данные авторизации</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'inn', $fieldOptions3)
            ->label(false)
            ->textInput(['placeholder' => 'ИНН организации']) ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => 'Логин'/*$model->getAttributeLabel('username')*/]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => 'Пароль'/*$model->getAttributeLabel('password')*/]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox()->label('Запомни меня') ?>
            </div>
            <div class="col-xs-4">
                <?= Html::submitButton('Вход', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
        </div>


        <?php ActiveForm::end(); ?>

        <!-- <div class="social-auth-links text-center">
            <p>- OR -</p>
            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in
                using Facebook</a>
            <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign
                in using Google+</a>
        </div> -->
        <!-- /.social-auth-links -->

        <!-- <a href="#">Забыл пароль</a><br> -->
        <!-- <a href="register.html" class="text-center">Register a new membership</a> -->

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

views/site/meters.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CompanySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Общедомовые прибооры учета';
$this->params['breadcrumbs'][] = 'Общедомовые приборы учета';

CrudAsset::register($this);

?>
    <div class="company-index">
        <div id="ajaxCrudDatatable">
            <?php try {
                echo GridView::widget([
                    'id' => 'crud-datatable',
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'pjax' => true,
                    'columns' => require(__DIR__ . '/_house_columns.php'),
                    'toolbar' => [
                        [
                            'content' =>

                                Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                                    ['data-pjax' => 1, 'class' => 'btn btn-default', 'title' => 'Reset Grid']) .
                                '{toggleData}' .
                                '{export}'
                        ],
                    ],
                    'striped' => true,
                    'condensed' => true,
                    'responsive' => true,
                    'panel' => [
                        'type' => 'primary',
                        'heading' => '<i class="glyphicon glyphicon-list"></i> Список компаний',
                        'after' =>
//                            BulkWidget::widget([
//                                'buttons' => Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All',
//                                    ["bulkdelete"],
//                                    [
//                                        "class" => "btn btn-danger btn-xs",
//                                        'role' => 'modal-remote-bulk',
//                                        'data-confirm' => false,
//                                        'data-method' => false,// for overide yii data api
//                                        'data-request-method' => 'post',
//                                        'data-confirm-title' => 'Вы уверены?',
//                                        'data-confirm-message' => 'Вы уверены, что хотите удалить эту запись?'
//                                    ]),
//                            ]) .
                            '<div class="clearfix"></div>',
                    ]
                ]);
            } catch (Exception $e) {
                Yii::error($e->getTraceAsString(), '_error');
                Yii::$app->session->setFlash('error', $e->getMessage());
            } ?>
        </div>
    </div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>